api:
    entities:
        Oro\Bundle\TaskBundle\Entity\Task:
            documentation_resource: '@OroTaskBundle/Resources/doc/api/task.md'
            fields:
                activityTargets:
                    data_type: association:manyToMany:activity

        Oro\Bundle\TaskBundle\Entity\TaskPriority:
            documentation_resource: '@OroTaskBundle/Resources/doc/api/task.md'

        Extend\Entity\EV_Task_Status:
            documentation_resource: '@OroTaskBundle/Resources/doc/api/task.md'
