api:
    entities:
        Oro\Bundle\TaskBundle\Entity\Task:
            documentation_resource: '@OroTaskBundle/Resources/doc/api/task.md'
            filters:
                fields:
                    ownerUsername:
                        data_type: string
                        property_path: owner.username
            fields:
                activityTargets:
                    data_type: association:manyToMany:activity
            subresources:
                createdBy:
                    actions:
                        get_subresource: true
                        get_relationship: true
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false

        Oro\Bundle\TaskBundle\Entity\TaskPriority:
            documentation_resource: '@OroTaskBundle/Resources/doc/api/task.md'

        Extend\Entity\EV_Task_Status:
            documentation_resource: '@OroTaskBundle/Resources/doc/api/task.md'
